/** Shared slug helpers for ATS probing and company matching. */

export function slugify(name) {
  return name
    .toLowerCase()
    .replace(/\([^)]*\)/g, "")
    .replace(/[^a-z0-9]+/g, "")
    .trim();
}

const SLUG_ALIASES = {
  apna: ["apna"],
  unacademy: ["unacademy"],
  nobroker: ["nobroker"],
  slice: ["slice", "sliceit", "slicepay"],
  turtlemint: ["turtlemint"],
  whatfix: ["whatfix"],
  kreditbee: ["kreditbee", "krazybee"],
  "urban company": ["urbancompany"],
  "apollo.io": ["apolloio", "apollo"],
  "cognida.ai": ["cognida"],
  "observe.ai": ["observeai"],
  "murf.ai": ["murf"],
  "smiles.ai": ["smilesai", "smiles"],
  "myways.ai": ["myways", "mywaysai"],
  "infra.market": ["inframarket", "infra"],
  alaan: ["alaan-careers", "alaan"],
  "synthio labs": ["synthiolabs", "synthio"],
  "sarvam ai": ["sarvam"],
  "skyroot aerospace": ["skyroot"],
  "go digit": ["godigit"],
  "bright money": ["brightmoney"],
  "clear feed": ["clearfeed"],
  "induced ai": ["induced", "inducedai"],
  "pulse energy": ["pulseenergy"],
  "chaos genius": ["chaosgenius"],
  "bobble ai": ["bobble", "bobbleai"],
  appsforbharat: ["appsforbharat", "srimandir"],
  "aye finance": ["ayefinance"],
  crowdanalytix: ["crowdanalytix"],
  "cosmoserve space": ["cosmoserve"],
  "sanyark space": ["sanyark"],
  "sharang shakti": ["sharangshakti"],
  "gimbal space": ["gimbalspace"],
  "fenix technologies": ["fenix"],
  "esports xo": ["esportsxo"],
  "validus fintech": ["validus"],
  loop: ["loophealth", "loopclub"],
  comet: ["cometshoes", "comet"],
  snabbit: ["snabbit"],
  giga: ["gigaai", "giga"],
  avoca: ["avoca", "avocaai"],
  promptql: ["promptql"],
  jify: ["jify"],
  venwiz: ["venwiz"],
  covvalent: ["covvalent"],
  investmint: ["investmint"],
  daolens: ["daolens"],
  metaforms: ["metaforms"],
  zoplar: ["zoplar"],
  mitigata: ["mitigata"],
  cellcolabs: ["cellcolabs"],
  languify: ["languify"],
  flint: ["flintmoney", "flint"],
  uniqus: ["uniqusconsultech", "uniqus"],
  globalfair: ["globalfair"],
  llumo: ["llumo"],
  swirepay: ["swirepay"],
  helogen: ["helogen"],
  krayonnz: ["krayonnz"],
  presolv360: ["presolv360"],
  zfunds: ["zfunds"],
  plotline: ["plotline"],
  curelink: ["curelink"],
  citymall: ["citymall"],
  atlys: ["atlys"],
  autoninja: ["autoninja"],
  axio: ["axio"],
  belong: ["belong"],
  airblack: ["airblack"],
  alle: ["alle"],
  "adopt ai": ["adoptai"],
  chaayos: ["chaayos"],
  boxs: ["boxs"],
  karban: ["karban"],
  zorro: ["zorro"],
  swish: ["swish"],
  lemmebe: ["lemmebe"],
  "true diamond": ["truediamond"],
  "inner fit": ["innerfit"],
  "second ocean": ["secondocean"],
  firstsense: ["firstsense"],
  neurowyzr: ["neurowyzr"],
  youshd: ["youshd"],
  "de shaw": ["deshaw", "deshawresearch"],
  "jp morgan": ["jpmorgan", "jpmorganchase"],
  "neuron7.ai": ["neuron7", "neuron7ai"],
  "branch international": ["branch", "branchco"],
  "stable money": ["stablemoney"],
  "network science": ["networkscience"],
  "confido health": ["confidohealth"],
  "greylabs ai": ["greylabs", "greylabsai"],
  "finster ai": ["finsterai", "finster"],
  openobserve: ["openobserve-careers", "openobserve"],
  neysa: ["neysanetwork", "neysa"],
  "relevance ai": ["relevanceai", "relevance"],
  "latent ai": ["latent", "latentai"],
  twilio: ["twilio"],
  servicenow: ["servicenow"],
  spot: ["spot", "spotai"],
  outmarketai: ["outmarketai", "outmarket"],
  cultfit: ["cultfit", "curefit"],
  okta: ["okta"],
  rippling: ["rippling"],
  navi: ["navi", "navitechnologies"],
  razorpay: ["razorpay", "razorpaysoftwareprivatelimited"],
  pocketfm: ["pocketfm", "pocket"],
  snabbit: ["snabbit"],
  kotak: ["kotak", "kotakmahindrabank"],
  skillz: ["skillz", "skillzinc"],
  spinny: ["spinny"],
  enterpret: ["enterpret"],
  uber: ["uber"],
  agoda: ["agoda"],
  quince: ["quince", "onequince"],
  zepto: ["zepto"],
  qiro: ["qiro"],
  clevertap: ["clevertap"],
  uipath: ["uipath"],
  "pramana.ai": ["pramana", "pramanaai"],
  "dp world": ["dpworld"],
  gohighlevel: ["gohighlevel", "highlevel"],
  highlevel: ["gohighlevel", "highlevel"],
  cred: ["cred"],
  stripe: ["stripe"],
  postman: ["postman"],
  "cure.fit": ["cultfit", "curefit"],
  grofers: ["blinkit", "grofers"],
  "d. e. shaw & co.": ["deshaw", "deshawresearch"],
  "tower research capital": ["towerresearch", "tower-research"],
  "app dynamics": ["appd", "appdynamics"],
  "ea games": ["ea", "electronicarts"],
  "goldman sachs": ["goldmansachs", "gs"],
  "jp morgan": ["jpmorgan", "jpmorganchase"],
  flipkart: ["flipkart"],
  swiggy: ["swiggy"],
  phonepe: ["phonepe"],
  paytm: ["paytm", "paytmcorp"],
  zerodha: ["zerodha"],
  zoho: ["zohocorp", "zoho"],
  atlassian: ["atlassian"],
  databricks: ["databricks"],
  cloudflare: ["cloudflare"],
  discord: ["discord"],
  coinbase: ["coinbase"],
  coindcx: ["coindcx"],
  "coinswitch kuber": ["coinswitch"],
  dream11: ["dream11", "dreamsports"],
  dunzo: ["dunzo"],
  delhivery: ["delhivery"],
  lenskart: ["lenskart"],
  myntra: ["myntra"],
  ola: ["olacabs", "ola"],
  oyo: ["oyo", "oyorooms"],
  upstox: ["upstox"],
  sharechat: ["sharechat"],
  chargebee: ["chargebee"],
  juspay: ["juspay"],
  cashfree: ["cashfree"],
  atlan: ["atlan"],
  rubrik: ["rubrik"],
  mongodb: ["mongodb"],
  hashicorp: ["hashicorp"],
  github: ["github"],
  gitlab: ["gitlab"],
  spotify: ["spotify"],
  netflix: ["netflix"],
  airbnb: ["airbnb"],
  doordash: ["doordash"],
  twitter: ["twitter", "x"],
  meta: ["meta", "facebook"],
  google: ["google", "alphabet"],
  amazon: ["amazon"],
  microsoft: ["microsoft"],
  apple: ["apple"],
  nvidia: ["nvidia"],
  amd: ["amd"],
  intel: ["intel"],
  qualcomm: ["qualcomm"],
  samsung: ["samsung"],
  siemens: ["siemens"],
  bosch: ["bosch", "boschgroup"],
  cisco: ["cisco"],
  oracle: ["oracle"],
  sap: ["sap"],
  ibm: ["ibm"],
  adobe: ["adobe"],
  salesforce: ["salesforce"],
  paypal: ["paypal"],
  visa: ["visa"],
  mastercard: ["mastercard"],
  "american express": ["americanexpress", "amex"],
  "morgan stanley": ["morganstanley"],
  barclays: ["barclays"],
  "hsbc bank": ["hsbc"],
  "deutsche bank": ["deutschebank"],
  "wells fargo": ["wellsfargo", "wf"],
  "citi bank": ["citi", "citigroup"],
  "hdfc bank": ["hdfc"],
  "axis bank": ["axisbank"],
  "kotak mahindra bank": ["kotak", "kotakmahindrabank"],
  acko: ["acko"],
  bharatpe: ["bharatpe"],
  bigbasket: ["bigbasket"],
  browserstack: ["browserstack"],
  "browser stack": ["browserstack"],
  byjus: ["byjus"],
  fractal: ["fractal"],
  geeksforgeeks: ["geeksforgeeks"],
  hackerearth: ["hackerearth"],
  hackerrank: ["hackerrank"],
  hashedin: ["hashedin", "deloitte"],
  inmobi: ["inmobi"],
  innovaccer: ["innovaccer"],
  khatabook: ["khatabook"],
  licious: ["licious"],
  magicpin: ["magicpin"],
  makemytrip: ["makemytrip"],
  mobikwik: ["mobikwik"],
  ninjacart: ["ninjacart"],
  pharmeasy: ["pharmeasy"],
  practo: ["practo"],
  squadstack: ["squadstack"],
  unacadamy: ["unacademy", "unacadamy"],
  "yellow.ai": ["yellowai", "yellow"],
  yugabyte: ["yugabyte"],
  zeta: ["zeta"],
  "booking.com": ["booking"],
  expedia: ["expedia", "expediagroup"],
  harness: ["harness"],
  freshworks: ["freshworks"],
  meesho: ["meesho"],
  "agnikul cosmos": ["agnikul"],
  "sarvam ai": ["sarvam"],
  krutrim: ["krutrim", "olakrutrim"],
  intuz: ["intuz"],
  uniphore: ["uniphore"],
  "fractal analytics": ["fractal", "fractalanalytics"],
  haptik: ["haptik"],
  "qure.ai": ["qure", "qureai"],
  sigtuple: ["sigtuple"],
  wysa: ["wysa"],
  niramai: ["niramai"],
  "mad street den": ["madstreetden", "madstreet"],
  "arya.ai": ["arya", "aryaai"],
  "pixis ai": ["pixis", "pixisai"],
  "gnani.ai": ["gnani", "gnaniai"],
  neuralgarage: ["neuralgarage"],
  "bolna ai": ["bolna", "bolnaai"],
  spyne: ["spyne"],
  accubits: ["accubits"],
  acquia: ["acquia"],
  "angel one": ["angelone", "angeloneindia"],
  appsmith: ["appsmith"],
  "cactus communications": ["cactus", "cactusglobal"],
  ciena: ["ciena"],
  cimpress: ["cimpress", "cimpressindia"],
  clickpost: ["clickpost"],
  coditation: ["coditation"],
  coriolis: ["coriolis", "coriolistechnologies"],
  coursera: ["coursera"],
  crowdstrike: ["crowdstrike"],
  "dell technologies": ["dell"],
  "dxc technology": ["dxc"],
  elsevier: ["elsevier", "relx"],
  "epam anywhere": ["epam", "epamsystems"],
  eventbrite: ["eventbrite"],
  greytip: ["greytip", "greythr"],
  "greytip software": ["greytip", "greythr"],
  "housing.com": ["housing", "housingcom"],
  infosys: ["infosys"],
  khoros: ["khoros"],
  "narayana group": ["narayana", "narayanahealth"],
  "nextgen healthcare": ["nextgen", "nextgenhealthcare"],
  noon: ["noon", "nooncom"],
  "nsr information system": ["nsr", "nsrit"],
  paralleldots: ["paralleldots"],
  peoplegrove: ["peoplegrove"],
  phyllo: ["phyllo", "getphyllo"],
  policybazaar: ["policybazaar", "pbpartners"],
  "polygon labs": ["polygon", "polygontechnology", "polygonlabs"],
  "priceWaterhouse coopers (pwc) service delivery centre bangalore": ["pwc", "pwcbangalore"],
  "publicis sapient": ["publicissapient", "sapient"],
  "push protocol": ["pushprotocol", "push"],
  remote: ["remote", "remotecom"],
  sedin: ["sedin", "sedintechnologies"],
  smallcase: ["smallcase"],
  springboard: ["springboard"],
  talentica: ["talentica", "talenticasoftware"],
  "tech prescient": ["techprescient"],
  techgrit: ["techgrit"],
  teradata: ["teradata"],
  themathcompany: ["themathcompany", "mathcompany"],
  trantor: ["trantor"],
  turing: ["turing", "turingcom"],
  vmware: ["vmware", "broadcom"],
  webnyay: ["webnyay"],
  yugabytedb: ["yugabyte"],
};

export function slugCandidates(name) {
  const slugs = new Set([slugify(name)]);
  const key = name.toLowerCase();

  if (SLUG_ALIASES[key]) {
    SLUG_ALIASES[key].forEach((s) => slugs.add(s));
  }

  name
    .toLowerCase()
    .split(/[\s./]+/)
    .filter((w) => w.length > 2)
    .forEach((w) => slugs.add(slugify(w)));

  return [...slugs];
}
